# Generated by Django 3.1.3 on 2020-11-11 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('pktsize', models.IntegerField(default=1)),
                ('lifetime', models.CharField(blank=True, max_length=100)),
                ('rmd_amount', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('total_receive', models.IntegerField(default=0)),
                ('total_sale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('process', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.item')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.item')),
            ],
        ),
    ]
