# Generated by Django 3.1.3 on 2020-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='lifetime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
