# Generated by Django 3.1.3 on 2020-11-12 03:32

from django.db import migrations, models
import inventory_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_auto_20201112_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryupdate',
            name='quantity',
            field=models.IntegerField(default=1, validators=[inventory_app.models.validate_qty]),
        ),
    ]
