# Generated by Django 3.1.3 on 2020-11-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_auto_20201112_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='category',
        ),
    ]
